### ISSUE TITLE
Discover UI PAth: check if it can be used with Rest connector

### ISSUE THREAD

**Issue by mbiciin** [camunda/connectors-bundle#62] opened 2022-12-09 16:53 UTC
__What should we do?__

1. Discover how we should send requests to UIPath. Check [Rocks guide](https://postman.uipath.rocks/#58fadde2-0a93-4074-8955-b2639f77795b)
2. Test using Postman
3. Test on dev using the rest connector

__Why should we do it?__

https://github.com/camunda/product-hub/issues/190#issuecomment-1330434736)

**Comment by tmetzke** [comment] 2022-12-21 08:28
@mbiciin, this is in `Done`, but the issue is still open. Either move this to an appropriate column or close it. If you close it, maybe add results as well (if there are any).

**Comment by mbiciin** [comment] 2022-12-21 19:53
Hi, 
Yes, the uipath can be used with rest connector. Here is the PR with a custom template #113. It will be possible to use it after we fix the bug reported here [#3251](https://github.com/camunda/web-modeler/issues/3251). 
Thank you,

**Closed** 2022-12-21 19:53 UTC
Labels: kind:task, scope:uipath
