### ISSUE TITLE
Add connectors SDK and bundle to supported environments page

### ISSUE THREAD

**Issue by sbuettner** [camunda/connectors-bundle#668] opened 2023-06-05 08:24 UTC
The connectors component should be part of the supported environments page:
https://docs.camunda.io/docs/next/reference/supported-environments/

**Comment by bastiankoerber** [comment] 2023-06-06 13:58
is it a duplicate of: [Add connectors bundle & SDK to suported environments docs#664](https://github.com/camunda/connectors-bundle/issues/664)

**Closed** 2023-07-05 12:03 UTC
